@startuml
hide circle

class 会員 {
  会員番号
  氏名
  生年月日
}

class 映画 {
  映画ID
  タイトル
  3D
}

class 上映 {
  上映ID
  映画ID
  スクリーンNo
  上映開始時間
  上映終了時間
  休日？()
  レイトショー？()
  映画の日？()
}

class チケットタイプ {
  チケットタイプ名称
  平日料金
  平日料金（レイトショー）
  休日料金
  休日料金（レイトショー）
  映画の日料金
  料金計算(平日か？, レイトショーか?, 映画の日か?)
}

package チケット発券集約 <<Rectangle>> {

class チケット {
  チケットNo
  料金
}

class チケット申込 {
  申込連番
  チケット料金
  会員番号
  3Dメガネあり
}

class チケット発券 {
  発券No
  上映ID
  合計金額
  発券()
}
}


チケット発券 "1" *-- "1..n" チケット申込
チケット申込 "1" -- "1" チケット
チケット発券 "0..n" -- "1" 上映
映画 "1" -- "1..n" 上映
チケット申込 "0..n" -- "1" 会員
チケット申込 "1" -- "1" チケットタイプ
@enduml