@startuml
hide circle

class 会員 {
  会員番号
  氏名
  生年月日
}

class 映画 {
  映画ID
  タイトル
  3D
}

class 上映 {
  上映ID
  映画ID
  スクリーンNo
  上映開始時間
  上映終了時間
  休日？()
  レイトショー？()
  映画の日？()
}

class スクリーン {
  スクリーンNo
  座席数
}

package チケット発券集約 <<Rectangle>> {

class チケット {
  チケットNo
  チケット種類
  料金
}

class チケット申込 {
  申込連番
  会員番号
  申込種別
  3Dメガネあり
}

class チケット発券 {
  発券No
  上映ID
  エムアイカードあり
  駐車場パーク80割引あり
  合計金額
  発券()
}
}


チケット発券 "1" *-- "1..n" チケット申込
チケット申込 "1" -- "1" チケット
チケット発券 "0..n" -- "1" 上映
映画 "1" -- "1..n" 上映
上映 "0..n" -- "1" スクリーン
チケット申込 "0..n" -- "1" 会員
@enduml